### ISSUE TITLE
popover array is missing when popover-placement is top-left bottom-left

### ISSUE THREAD

**Issue by mindej** [Morgul/ui-bootstrap4#25]
To reproduce go to 

https://morgul.github.io/ui-bootstrap4/

![image](https://user-images.githubusercontent.com/1636250/41040288-add05c82-69a4-11e8-8274-36dd0704b206.png)

**Comment by Morgul** [comment]
![image](https://user-images.githubusercontent.com/770655/41778983-f7fc1c08-75f5-11e8-9ac5-6dee8aab5dcc.png)

The arrow positioning code is horribly broken; and my few hacks to it have fixed the very slim use case I had, but it's really a mess.

I would love to get some help fixing it; I've spent a few hours and are no closer to understanding how that code originally functioned than I am now, let alone coming up with a fix. Alternatively, the project could be ported to using [popper.js](https://popper.js.org/).

**Comment by DarkNami** [comment]
Bootstrap 4 only provide 'top, bottom, left, right' 4 placements, you have to add 'top-left' by self.

This is 'left-top' for Bootstrap v4.3.1:
```css
.bs-popover-auto[x-placement^="left-top"], .bs-popover-left-top {
	margin-right: .5rem;
}

.bs-popover-auto[x-placement^="left-top"] > .arrow::before, .bs-popover-left-top > .arrow::before {
	right: 0;
	border-width: .5rem 0 .5rem .5rem;
	border-left-color: rgba(0,0,0,.25);
}

.bs-popover-auto[x-placement^="left-top"] > .arrow::after, .bs-popover-left-top > .arrow::after {
	right: 1px;
	border-width: .5rem 0 .5rem .5rem;
	border-left-color: #fff;
}

.bs-popover-auto[x-placement^="left-top"] .arrow, .bs-popover-left-top .arrow {
	right: calc(-0.5rem);
	width: .5rem;
	height: 1rem;
	margin: .3rem 0;
}
```
![圖片](https://user-images.githubusercontent.com/5100919/60703197-bf1ce080-9f33-11e9-931d-3bf711d624bf.png)
